# Generated by Django 6.0.6 on 2026-07-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='phone',
        ),
    ]
