# Generated by Django 6.0.6 on 2026-07-12 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_remove_cv_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='name_surname',
        ),
    ]
