# Generated by Django 6.0.6 on 2026-07-12 22:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_remove_cv_name_surname'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companymember',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='companymember',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyzer.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together={('company', 'user', 'location')},
        ),
    ]
