# Generated by Django 6.0.6 on 2026-07-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='email',
            field=models.EmailField(default='aaa', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companymember',
            name='name_surname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
