# Generated by Django 6.0.6 on 2026-07-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_companymember_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='applicant',
            new_name='user',
        ),
        migrations.AddField(
            model_name='companymember',
            name='still_member',
            field=models.BooleanField(default=True),
        ),
    ]
