# Generated by Django 6.0.6 on 2026-07-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_companymember_email_companymember_name_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymember',
            name='email',
        ),
    ]
