# Generated by Django 6.0.6 on 2026-07-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_remove_companymember_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='num_views',
            field=models.IntegerField(default=0),
        ),
    ]
