# Generated by Django 6.0.6 on 2026-07-13 00:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_rename_applicant_cv_user_companymember_still_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companymember',
            unique_together={('company', 'user', 'location', 'created_at')},
        ),
        migrations.RemoveField(
            model_name='companymember',
            name='name_surname',
        ),
    ]
