# Generated by Django 6.0.6 on 2026-07-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_job_num_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillmatch',
            name='outdated',
            field=models.BooleanField(default=False),
        ),
    ]
